features_annotations_nlp =  {
  "name": "Natural Language Processing (NLP)",
  "description": "NLP-based annotation features for labeling and processing textual data.",
  "sub_features_1": [
    {
      "name": "Text Annotation",
      "description": "Core features for annotating and processing text.",
      "sub_features_2": [
        {
          "name": "Question Answering",
          "description": "Add annotations to answer questions based on the given text."
        },
        {
          "name": "Text Classification",
          "description": "Classify text into specific categories or labels."
        },
        {
          "name": "Named Entity Recognition (NER)",
          "description": "Annotate entities such as persons, locations, and organizations in the text."
        },
        {
          "name": "Taxonomy",
          "description": "Create hierarchical annotations to categorize and structure data."
        },
        {
          "name": "Relation Extraction",
          "description": "Annotate relationships between entities within the text."
        }
      ]
    },
    {
      "name": "Advanced Text Processing",
      "description": "Features for advanced text analysis and summarization.",
      "sub_features_2": [
        {
          "name": "Text Summarization",
          "description": "Summarize long text into shorter annotations."
        },
        {
          "name": "Part-of-Speech (POS) Tagging",
          "description": "Add grammatical category labels to each word in the text (e.g., noun, verb, adjective)."
        },
        {
          "name": "Dependency Parsing",
          "description": "Mark grammatical relationships between words to understand sentence structure and dependencies."
        },
        {
          "name": "Coreference Resolution",
          "description": "Annotate references that point to the same entity in the text (e.g., 'he' refers to 'John')."
        },
        {
          "name": "Topic Modeling",
          "description": "Group text into detected topics and provide annotations based on the topic distribution."
        }
      ]
    },
    {
      "name": "Sentiment and Emotion Analysis",
      "description": "Features for analyzing sentiment and emotions in text.",
      "sub_features_2": [
        {
          "name": "Sentiment Analysis",
          "description": "Annotate text sentiment as positive, negative, or neutral."
        },
        {
          "name": "Emotion Detection",
          "description": "Annotate the emotions expressed in the text, such as happy, sad, angry, or fearful."
        }
      ]
    },
    {
      "name": "Language and Similarity",
      "description": "Features for language detection and text similarity scoring.",
      "sub_features_2": [
        {
          "name": "Language Detection",
          "description": "Annotate the language used in the text, especially for multilingual cases."
        },
        {
          "name": "Keyphrase Extraction",
          "description": "Extract key phrases or keywords from text and add annotations for the most relevant ones."
        },
        {
          "name": "Text Similarity Scoring",
          "description": "Add similarity score annotations between two texts to measure how similar the content or context is."
        }
      ]
    },
    {
      "name": "Advanced NLP Features",
      "description": "Advanced NLP features for deeper understanding and generation.",
      "sub_features_2": [
        {
          "name": "Text Entailment",
          "description": "Mark the relationship between two sentences to indicate if one sentence implies or contradicts the other."
        },
        {
          "name": "Paraphrase Detection",
          "description": "Annotate text that contains sentences or phrases conveying the same meaning in different forms."
        },
        {
          "name": "Discourse Analysis",
          "description": "Annotate discourse structure, such as logical relationships between sentences or paragraphs."
        },
        {
          "name": "Intent Detection",
          "description": "Annotate the intent or purpose of text, often used in chatbots or conversational analysis (e.g., product orders, information requests)."
        },
        {
          "name": "Language Generation Validation",
          "description": "Annotate and assess the validity of text generated by NLP models to ensure context-appropriate results."
        }
      ]
    },
    {
      "name": "Text Summarization Methods",
      "description": "Detailed summarization techniques with various methods.",
      "sub_features_2": [
        {
          "name": "Automatic Summarization",
          "description": "Automatically generate summaries from text using pre-trained models."
        },
        {
          "name": "Extractive Summarization",
          "description": "Extract the most important sentences from the original text to create a summary."
        },
        {
          "name": "Abstractive Summarization",
          "description": "Rewrite new sentences that capture the essence of the original text, providing a more concise summary."
        },
        {
          "name": "Custom Length Summarization",
          "description": "Allow users to choose the summary length, such as 20%, 50%, or 70% of the original text."
        },
        {
          "name": "Keypoint Summary",
          "description": "Identify and summarize key points from paragraphs to highlight the most important information."
        }
      ]
    }
  ]
}
