import React, { useState } from "react";
import {
  FaChartLine,
  FaChartPie,
  FaChartBar,
  FaThLarge,
  FaProjectDiagram,
  FaImage,
} from "react-icons/fa";

export const templates: Template[] = [
  {
    id: 1,
    category: "Bar chart race",
    type: ["Bars", "Animated"],
    purpose: ["Comparison", "Ranking"],
    title: "Bar Chart Race",
    description: "Animated bar chart race.",
    icon: <FaChartBar />,
    image_url: "http://127.0.0.1:8000/static/images/data_visualization/bar-chart-race.png",
    inputDataType: ["Categorical", "Numerical"],
    numFields: 2,
    fieldTypes: ["String", "Number"],
    outputType: ["Animated Visualization"],
  },
    {
      id: 2,
      category: "Bar chart race",
      type: ["Bars", "Animated"],
      purpose: ["Change over time"],
      title: "Column Chart Race",
      description: "Column chart race animation.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: ["Time Series", "Categorical"],
      numFields: 3,
      fieldTypes: ["Date", "String", "Number"],
      outputType: ["Animated Visualization"],
    },
    {
      id: 3,
      category: "Line, Bar and Pie Charts",
      type: ["Lines"],
      purpose: ["Comparison", "Change over time"],
      title: "Line Chart",
      description: "A basic line chart.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: ["Time Series"],
      numFields: 2,
      fieldTypes: ["Date", "Number"],
      outputType: ["Static Visualization"],
    },
    {
      id: 4,
      category: "Line, Bar and Pie Charts",
      type: ["Lines"],
      purpose: ["Projection"],
      title: "Line Chart (Projected)",
      description: "A line chart with projections.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: ["Time Series", "Numerical"],
      numFields: 3,
      fieldTypes: ["Date", "Number", "Number"],
      outputType: ["Static Visualization", "Projections"],
    },
    {
      id: 5,
      category: "Line, Bar and Pie Charts",
      type: ["Lines"],
      purpose: ["Searchable"],
      title: "Line Chart (Searchable)",
      description: "A line chart with searchable series.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 6,
      category: "Line, Bar and Pie Charts",
      type: ["Lines"],
      purpose: ["Highlight"],
      title: "Line Chart (With Highlight)",
      description: "A line chart with highlighted areas.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 7,
      category: "Line, Bar and Pie Charts",
      type: ["Areas"],
      purpose: ["Proportional"],
      title: "Area Chart (Proportional)",
      description: "An area chart showing proportions.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 8,
      category: "Line, Bar and Pie Charts",
      type: ["Areas"],
      purpose: ["Stacked"],
      title: "Area Chart (Stacked)",
      description: "A stacked area chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 9,
      category: "Line, Bar and Pie Charts",
      type: ["Bars"],
      purpose: ["Comparison"],
      title: "Bar Chart",
      description: "A basic bar chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 10,
      category: "Line, Bar and Pie Charts",
      type: ["Bars"],
      purpose: ["Proportional"],
      title: "Bar Chart (Proportional)",
      description: "A proportional bar chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 11,
      category: "Line, Bar and Pie Charts",
      type: ["Bars"],
      purpose: ["Stacked"],
      title: "Bar Chart (Stacked)",
      description: "A stacked bar chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 12,
      category: "Line, Bar and Pie Charts",
      type: ["Pies"],
      purpose: ["Part-to-whole"],
      title: "Pie Chart",
      description: "A pie chart to visualize proportions.",
      icon: <FaChartPie />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: ["Categorical", "Numerical"],
      numFields: 2,
      fieldTypes: ["String", "Number"],
      outputType: ["Static Visualization"],
    },
    {
      id: 13,
      category: "Line, Bar and Pie Charts",
      type: ["Pies"],
      purpose: ["Time slider"],
      title: "Donut Chart with Time Slider",
      description: "A dynamic donut chart with a time slider.",
      icon: <FaChartPie />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 15,
      category: "Hierarchy",
      type: ["Hierarchy"],
      purpose: ["Part-to-whole"],
      title: "Hierarchical Bars",
      description: "Hierarchical bar chart.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 16,
      category: "Hierarchy",
      type: ["Radial"],
      purpose: ["Hierarchy"],
      title: "Sunburst",
      description: "Circular hierarchy.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 17,
      category: "Sankey diagram",
      type: ["Lines", "Interactive content"],
      purpose: ["Flow", "Hierarchy"],
      title: "Sankey",
      description: "Flow diagram for processes.",
      icon: <FaProjectDiagram />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: ["Categorical", "Numerical"],
      numFields: 3,
      fieldTypes: ["String", "String", "Number"],
      outputType: ["Interactive Visualization"],
    },
    {
      id: 18,
      category: "Sankey diagram",
      type: ["Lines", "Interactive content"],
      purpose: ["Flow", "Hierarchy"],
      title: "Alluvial",
      description: "Show flow by categories.",
      icon: <FaProjectDiagram />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 19,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Bars"],
      purpose: ["Comparison"],
      title: "Waterfall chart",
      description:
        "Waterfall charts are a variation of column chart, showing a breakdown of a values or change over time when negative and positive values are involved.",
      icon: <FaProjectDiagram />,
      image_url: "https://via.placeholder.com/150/1",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 20,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Filters"],
      purpose: ["Comparison"],
      title: "Bar Chart (With Filter)",
      description: "A bar chart with filtering options.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/20",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 21,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Bars"],
      purpose: ["Combination"],
      title: "Column + Line",
      description: "A combination of column and line charts.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/21",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 22,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Areas"],
      purpose: ["Combination"],
      title: "Line + Area",
      description: "A combination of line and area charts.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/22",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 23,
      category: "Line, Bar and Pie Charts",
      type: ["Columns"],
      purpose: ["Comparison"],
      title: "Column Chart",
      description: "A basic column chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/23",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 24,
      category: "Line, Bar and Pie Charts",
      type: ["Columns", "Grouped"],
      purpose: ["Comparison"],
      title: "Column Chart (Grouped)",
      description: "A grouped column chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/24",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 25,
      category: "Line, Bar and Pie Charts",
      type: ["Columns", "Proportional"],
      purpose: ["Part-to-whole"],
      title: "Column Chart (Proportional)",
      description: "A proportional column chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/25",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 26,
      category: "Line, Bar and Pie Charts",
      type: ["Columns", "Stacked"],
      purpose: ["Comparison"],
      title: "Column Chart (Stacked)",
      description: "A stacked column chart.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/26",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 27,
      category: "Line, Bar and Pie Charts",
      type: ["Columns", "Highlight"],
      purpose: ["Highlighting"],
      title: "Column Chart (With Highlight)",
      description: "A column chart with highlighted areas.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/27",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 28,
      category: "Line, Bar and Pie Charts",
      type: ["Pies"],
      purpose: ["Part-to-whole"],
      title: "Donut Chart",
      description: "A simple donut chart.",
      icon: <FaChartPie />,
      image_url: "https://via.placeholder.com/150/28",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 29,
      category: "Line, Bar and Pie Charts",
      type: ["Pies", "Dynamic"],
      purpose: ["Time-based analysis"],
      title: "Donut Chart with Time Slider",
      description: "A dynamic donut chart with a time slider.",
      icon: <FaChartPie />,
      image_url: "https://via.placeholder.com/150/29",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 30,
      category: "Line, Bar and Pie Charts",
      type: ["Areas", "Grid"],
      purpose: ["Comparison"],
      title: "Grid of Area Charts",
      description: "A grid layout of multiple area charts.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/30",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 31,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Grid"],
      purpose: ["Comparison"],
      title: "Grid of Bar Charts",
      description: "A grid layout of multiple bar charts.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/31",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 32,
      category: "Line, Bar and Pie Charts",
      type: ["Pies", "Grid"],
      purpose: ["Part-to-whole"],
      title: "Grid of Donut Charts",
      description: "A grid layout of multiple donut charts.",
      icon: <FaChartPie />,
      image_url: "https://via.placeholder.com/150/32",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 34,
      category: "Line, Bar and Pie Charts",
      type: ["Bars"],
      purpose: ["Demographics"],
      title: "Population Pyramid",
      description: "A pyramid chart showing population distributions.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/34",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 35,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Stream"],
      purpose: ["Flow", "Change over time"],
      title: "Streamgraph",
      description: "A streamgraph showing changes over time.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/35",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 36,
      category: "Line, Bar and Pie Charts",
      type: ["Areas", "Bump"],
      purpose: ["Comparison", "Change over time"],
      title: "Area Bump Chart",
      description: "A bump chart using area visualizations.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/36",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 37,
      category: "Line, Bar and Pie Charts",
      type: ["Areas", "Bump", "Proportional"],
      purpose: ["Part-to-whole"],
      title: "Area Bump Chart (Proportional)",
      description: "A proportional bump chart using areas.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/37",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 38,
      category: "Line, Bar and Pie Charts",
      type: ["Areas", "Highlight"],
      purpose: ["Highlighting", "Comparison"],
      title: "Area Chart (With Color Highlight)",
      description: "An area chart with highlighted regions.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/38",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 39,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Barcode"],
      purpose: ["Comparison", "Patterns"],
      title: "Barcode Plot",
      description: "A barcode plot for pattern analysis.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/39",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 40,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Likert"],
      purpose: ["Survey", "Comparison"],
      title: "Column Chart (Likert Scale)",
      description: "A column chart for Likert scale data representation.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/40",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 41,
      category: "Line, Bar and Pie Charts",
      type: ["Custom", "Grid"],
      purpose: ["Geography", "Comparison"],
      title: "Custom Grid (Europe)",
      description: "A custom grid layout for Europe data visualization.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/41",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 42,
      category: "Line, Bar and Pie Charts",
      type: ["Custom", "Grid"],
      purpose: ["Geography", "Comparison"],
      title: "Custom Grid (France)",
      description: "A custom grid layout for France data visualization.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/42",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 43,
      category: "Line, Bar and Pie Charts",
      type: ["Custom", "Grid"],
      purpose: ["Patterns", "Comparison"],
      title: "Custom Grid (Circles)",
      description: "A custom grid layout using circles.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/43",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 44,
      category: "Line, Bar and Pie Charts",
      type: ["Custom", "Grid"],
      purpose: ["Patterns", "Comparison"],
      title: "Custom Grid (Columns)",
      description: "A custom grid layout using columns.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/44",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 45,
      category: "Line, Bar and Pie Charts",
      type: ["Custom", "Grid"],
      purpose: ["Patterns", "Comparison"],
      title: "Custom Grid (Line)",
      description: "A custom grid layout using lines.",
      icon: <FaThLarge />,
      image_url: "https://via.placeholder.com/150/45",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 46,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Cycle"],
      purpose: ["Seasonality", "Patterns"],
      title: "Cycle Plot",
      description: "A plot to analyze seasonality patterns.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/46",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 47,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Diverging"],
      purpose: ["Comparison", "Opinion"],
      title: "Diverging Bar Chart",
      description: "A bar chart for showing diverging opinions or values.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/47",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 48,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Diverging", "Stacked"],
      purpose: ["Comparison", "Opinion"],
      title: "Diverging Stacked Bar Chart",
      description: "A stacked bar chart with diverging values.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/48",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 49,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Fan"],
      purpose: ["Forecasting", "Comparison"],
      title: "Fan Chart",
      description: "A chart to visualize forecasting ranges.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/49",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 50,
      category: "Line, Bar and Pie Charts",
      type: ["Grid", "Charts"],
      purpose: ["Comparison", "Shading"],
      title: "Grid of Charts with Shading",
      description: "A grid of charts with shaded areas to emphasize trends.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/50",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 51,
      category: "Line, Bar and Pie Charts",
      type: ["Grid", "Columns", "Stacked"],
      purpose: ["Comparison", "Aggregation"],
      title: "Grid of Column Charts (Stacked)",
      description:
        "A grid of stacked column charts for aggregation visualization.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/51",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 52,
      category: "Line, Bar and Pie Charts",
      type: ["Grid", "Lines"],
      purpose: ["Comparison", "Trends"],
      title: "Grid of Line Charts",
      description: "A grid of line charts for comparing multiple trends.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/52",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 53,
      category: "Line, Bar and Pie Charts",
      type: ["Grid", "Pies"],
      purpose: ["Part-to-whole", "Comparison"],
      title: "Grid of Pie Charts",
      description: "A grid of pie charts for part-to-whole comparisons.",
      icon: <FaChartPie />,
      image_url: "https://via.placeholder.com/150/53",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 54,
      category: "Line, Bar and Pie Charts",
      type: ["Histogram"],
      purpose: ["Distribution", "Frequency"],
      title: "Histogram",
      description: "A chart to visualize the frequency distribution of data.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/54",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 55,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Bump"],
      purpose: ["Comparison", "Trends"],
      title: "Line Bump Chart",
      description: "A bump chart to show rankings over time.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/55",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 56,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Comparison"],
      purpose: ["Year-on-Year"],
      title: "Line Chart (Year-on-Year Comparison)",
      description: "A line chart for year-on-year data comparisons.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/56",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 57,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Performance"],
      purpose: ["Comparison", "Performance"],
      title: "Performance Bars",
      description: "Bars to showcase performance metrics.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/57",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 58,
      category: "Line, Bar and Pie Charts",
      type: ["Seismogram"],
      purpose: ["Trends", "Events"],
      title: "Seismogram",
      description: "A chart to visualize seismic events or data.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/58",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 59,
      category: "Line, Bar and Pie Charts",
      type: ["Sparklines"],
      purpose: ["Trends", "Micro"],
      title: "Sparklines",
      description: "Tiny charts to show quick trends in small spaces.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/59",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 60,
      category: "Line, Bar and Pie Charts",
      type: ["Lines", "Steps"],
      purpose: ["Comparison", "Trends"],
      title: "Step Chart",
      description: "A step chart to show sudden changes in data over time.",
      icon: <FaChartLine />,
      image_url: "https://via.placeholder.com/150/60",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 61,
      category: "Line, Bar and Pie Charts",
      type: ["Areas"],
      purpose: ["Surplus", "Deficit"],
      title: "Surplus / Deficit Area Chart",
      description: "An area chart to highlight surplus and deficit data.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/61",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
    {
      id: 62,
      category: "Line, Bar and Pie Charts",
      type: ["Bars", "Survey"],
      purpose: ["Comparison", "Survey"],
      title: "Survey Bars",
      description:
        "Bar charts specifically designed for survey data visualization.",
      icon: <FaChartBar />,
      image_url: "https://via.placeholder.com/150/62",
      inputDataType: [],
      numFields: 0,
      fieldTypes: [],
      outputType: [],
    },
  ];