"""add AnnotationProjectFeaturesModel and AnnotationProjectSubFeaturesModel

Revision ID: 0101f2a9e42c
Revises: a415b2e0ace7
Create Date: 2024-12-26 14:51:31.094328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0101f2a9e42c'
down_revision = 'a415b2e0ace7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_project_features_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_features_tbl_id'), 'annotation_project_features_tbl', ['id'], unique=False)
    op.create_table('annotation_project_sub_features_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['annotation_project_features_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_sub_features_tbl_id'), 'annotation_project_sub_features_tbl', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_project_sub_features_tbl_id'), table_name='annotation_project_sub_features_tbl')
    op.drop_table('annotation_project_sub_features_tbl')
    op.drop_index(op.f('ix_annotation_project_features_tbl_id'), table_name='annotation_project_features_tbl')
    op.drop_table('annotation_project_features_tbl')
    # ### end Alembic commands ###
