"""Initial migration

Revision ID: 0129318b24a3
Revises: 
Create Date: 2025-01-18 12:47:02.184904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0129318b24a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('user_photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('menu_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('menu_metadata', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_menu_tbl_id'), 'menu_tbl', ['id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('delivery_type', postgresql.ENUM('EMAIL', 'SMS', 'WHATSAPP', name='deliverytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_verification_codes_phone_number'), 'verification_codes', ['phone_number'], unique=False)
    op.create_table('annotation_feature_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_annotation_feature_tbl_id'), 'annotation_feature_tbl', ['id'], unique=False)
    op.create_table('sub_feature_1_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['annotation_feature_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_feature_1_tbl_id'), 'sub_feature_1_tbl', ['id'], unique=False)
    op.create_table('sub_feature_2_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sub_feature_1_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_feature_1_id'], ['sub_feature_1_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_feature_2_tbl_id'), 'sub_feature_2_tbl', ['id'], unique=False)
    op.create_table('annotation_projects_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_photo_url', sa.String(), nullable=True),
    sa.Column('sub_feature_2_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_feature_2_id'], ['sub_feature_2_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_projects_tbl_id'), 'annotation_projects_tbl', ['id'], unique=False)
    op.create_table('annotation_project_data_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('IMAGE', 'AUDIO', 'TEXT', 'VIDEO', name='datatypeenum'), nullable=False),
    sa.Column('drafts', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_data_tbl_id'), 'annotation_project_data_tbl', ['id'], unique=False)
    op.create_table('annotation_project_deployments_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_deployments_tbl_id'), 'annotation_project_deployments_tbl', ['id'], unique=False)
    op.create_table('classes_and_tags_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('class_color', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_and_tags_tbl_id'), 'classes_and_tags_tbl', ['id'], unique=False)
    op.create_table('models_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.Enum('INTERNAL_MODEL', 'EXTERNAL_MODEL', name='modeltypeenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_tbl_id'), 'models_tbl', ['id'], unique=False)
    op.create_table('active_learning_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['annotation_project_deployments_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_learning_tbl_id'), 'active_learning_tbl', ['id'], unique=False)
    op.create_table('audio_annotation_result_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_annotation_result_tbl_id'), 'audio_annotation_result_tbl', ['id'], unique=False)
    op.create_table('audio_metadata_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_metadata_tbl_id'), 'audio_metadata_tbl', ['id'], unique=False)
    op.create_table('dataset_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_tbl_id'), 'dataset_tbl', ['id'], unique=False)
    op.create_table('deployment_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['annotation_project_deployments_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_tbl_id'), 'deployment_tbl', ['id'], unique=False)
    op.create_table('image_annotation_result_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_annotation_result_tbl_id'), 'image_annotation_result_tbl', ['id'], unique=False)
    op.create_table('image_metadata_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('color_mode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_metadata_tbl_id'), 'image_metadata_tbl', ['id'], unique=False)
    op.create_table('text_annotation_result_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('text_result', sa.Text(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_annotation_result_tbl_id'), 'text_annotation_result_tbl', ['id'], unique=False)
    op.create_table('text_metadata_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('encoding', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_metadata_tbl_id'), 'text_metadata_tbl', ['id'], unique=False)
    op.create_table('train_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_tbl_id'), 'train_tbl', ['id'], unique=False)
    op.create_table('version_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tbl_id'), 'version_tbl', ['id'], unique=False)
    op.create_table('video_annotation_result_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_annotation_result_tbl_id'), 'video_annotation_result_tbl', ['id'], unique=False)
    op.create_table('video_metadata_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_metadata_tbl_id'), 'video_metadata_tbl', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_metadata_tbl_id'), table_name='video_metadata_tbl')
    op.drop_table('video_metadata_tbl')
    op.drop_index(op.f('ix_video_annotation_result_tbl_id'), table_name='video_annotation_result_tbl')
    op.drop_table('video_annotation_result_tbl')
    op.drop_index(op.f('ix_version_tbl_id'), table_name='version_tbl')
    op.drop_table('version_tbl')
    op.drop_index(op.f('ix_train_tbl_id'), table_name='train_tbl')
    op.drop_table('train_tbl')
    op.drop_index(op.f('ix_text_metadata_tbl_id'), table_name='text_metadata_tbl')
    op.drop_table('text_metadata_tbl')
    op.drop_index(op.f('ix_text_annotation_result_tbl_id'), table_name='text_annotation_result_tbl')
    op.drop_table('text_annotation_result_tbl')
    op.drop_index(op.f('ix_image_metadata_tbl_id'), table_name='image_metadata_tbl')
    op.drop_table('image_metadata_tbl')
    op.drop_index(op.f('ix_image_annotation_result_tbl_id'), table_name='image_annotation_result_tbl')
    op.drop_table('image_annotation_result_tbl')
    op.drop_index(op.f('ix_deployment_tbl_id'), table_name='deployment_tbl')
    op.drop_table('deployment_tbl')
    op.drop_index(op.f('ix_dataset_tbl_id'), table_name='dataset_tbl')
    op.drop_table('dataset_tbl')
    op.drop_index(op.f('ix_audio_metadata_tbl_id'), table_name='audio_metadata_tbl')
    op.drop_table('audio_metadata_tbl')
    op.drop_index(op.f('ix_audio_annotation_result_tbl_id'), table_name='audio_annotation_result_tbl')
    op.drop_table('audio_annotation_result_tbl')
    op.drop_index(op.f('ix_active_learning_tbl_id'), table_name='active_learning_tbl')
    op.drop_table('active_learning_tbl')
    op.drop_index(op.f('ix_models_tbl_id'), table_name='models_tbl')
    op.drop_table('models_tbl')
    op.drop_index(op.f('ix_classes_and_tags_tbl_id'), table_name='classes_and_tags_tbl')
    op.drop_table('classes_and_tags_tbl')
    op.drop_index(op.f('ix_annotation_project_deployments_tbl_id'), table_name='annotation_project_deployments_tbl')
    op.drop_table('annotation_project_deployments_tbl')
    op.drop_index(op.f('ix_annotation_project_data_tbl_id'), table_name='annotation_project_data_tbl')
    op.drop_table('annotation_project_data_tbl')
    op.drop_index(op.f('ix_annotation_projects_tbl_id'), table_name='annotation_projects_tbl')
    op.drop_table('annotation_projects_tbl')
    op.drop_index(op.f('ix_sub_feature_2_tbl_id'), table_name='sub_feature_2_tbl')
    op.drop_table('sub_feature_2_tbl')
    op.drop_index(op.f('ix_sub_feature_1_tbl_id'), table_name='sub_feature_1_tbl')
    op.drop_table('sub_feature_1_tbl')
    op.drop_index(op.f('ix_annotation_feature_tbl_id'), table_name='annotation_feature_tbl')
    op.drop_table('annotation_feature_tbl')
    op.drop_index(op.f('ix_verification_codes_phone_number'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_menu_tbl_id'), table_name='menu_tbl')
    op.drop_table('menu_tbl')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
