"""add class_color in classesandtags  models

Revision ID: 08ac7b0dc94c
Revises: ef05d8830fd7
Create Date: 2025-01-03 10:34:01.932684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ac7b0dc94c'
down_revision = 'ef05d8830fd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
