"""add image_url in uploaddata models

Revision ID: 0c0e27393972
Revises: 4ce210653626
Create Date: 2025-01-02 22:21:34.496431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0e27393972'
down_revision = '4ce210653626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_data_tbl', sa.Column('img_url', sa.Text(), nullable=True))
    op.drop_column('upload_data_tbl', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_data_tbl', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('upload_data_tbl', 'img_url')
    # ### end Alembic commands ###
