"""add class_color in classesandtags  models

Revision ID: 13bec33e2d55
Revises: 93d85fb40361
Create Date: 2025-01-03 11:15:50.722019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bec33e2d55'
down_revision = '93d85fb40361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes_and_tags_tbl', 'tag_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes_and_tags_tbl', 'tag_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
