"""change upload data model

Revision ID: 4400a8a6c295
Revises: a0f54f0c32cd
Create Date: 2024-12-31 16:22:48.696258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4400a8a6c295'
down_revision = 'a0f54f0c32cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_data_tbl', sa.Column('project_id', sa.Integer(), nullable=False))
    op.alter_column('upload_data_tbl', 'data_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'upload_data_tbl', 'annotation_projects_tbl', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_data_tbl', type_='foreignkey')
    op.alter_column('upload_data_tbl', 'data_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('upload_data_tbl', 'project_id')
    # ### end Alembic commands ###
