"""add image_url

Revision ID: 68ca8ec25f5c
Revises: 0101f2a9e42c
Create Date: 2024-12-26 14:53:39.400511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ca8ec25f5c'
down_revision = '0101f2a9e42c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_project_features_tbl', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('annotation_project_sub_features_tbl', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_project_sub_features_tbl', 'image_url')
    op.drop_column('annotation_project_features_tbl', 'image_url')
    # ### end Alembic commands ###
