"""add class_color in classesandtags  models

Revision ID: 93d85fb40361
Revises: c745174116e6
Create Date: 2025-01-03 11:10:22.814613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d85fb40361'
down_revision = 'c745174116e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes_and_tags_tbl', sa.Column('class_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes_and_tags_tbl', 'class_name')
    # ### end Alembic commands ###
