"""change upload data model

Revision ID: a4d72e5829f8
Revises: 4400a8a6c295
Create Date: 2024-12-31 16:32:51.106454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d72e5829f8'
down_revision = '4400a8a6c295'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('upload_data_tbl_data_id_fkey', 'upload_data_tbl', type_='foreignkey')
    op.drop_column('upload_data_tbl', 'data_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_data_tbl', sa.Column('data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('upload_data_tbl_data_id_fkey', 'upload_data_tbl', 'annotation_project_data_tbl', ['data_id'], ['id'])
    # ### end Alembic commands ###
