"""add class_color in classesandtags  models

Revision ID: c39eeec2f026
Revises: 0c0e27393972
Create Date: 2025-01-03 10:31:01.082881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39eeec2f026'
down_revision = '0c0e27393972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes_and_tags_tbl', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('classes_and_tags_tbl', sa.Column('class_color', sa.String(), nullable=True))
    op.drop_constraint('classes_and_tags_tbl_data_id_fkey', 'classes_and_tags_tbl', type_='foreignkey')
    op.create_foreign_key(None, 'classes_and_tags_tbl', 'annotation_projects_tbl', ['project_id'], ['id'])
    op.drop_column('classes_and_tags_tbl', 'data_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes_and_tags_tbl', sa.Column('data_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classes_and_tags_tbl', type_='foreignkey')
    op.create_foreign_key('classes_and_tags_tbl_data_id_fkey', 'classes_and_tags_tbl', 'annotation_project_data_tbl', ['data_id'], ['id'])
    op.drop_column('classes_and_tags_tbl', 'class_color')
    op.drop_column('classes_and_tags_tbl', 'project_id')
    # ### end Alembic commands ###
