"""add class_color in classesandtags  models

Revision ID: c745174116e6
Revises: 08ac7b0dc94c
Create Date: 2025-01-03 10:38:40.587882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c745174116e6'
down_revision = '08ac7b0dc94c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
