"""Initial migration

Revision ID: d2a3e8325edb
Revises: 68ca8ec25f5c
Create Date: 2024-12-26 14:58:56.667755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a3e8325edb'
down_revision = '68ca8ec25f5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
