"""add image_url in upload data  model

Revision ID: d54c1f7a67a2
Revises: a13fd38a2e18
Create Date: 2025-01-02 21:54:24.725820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54c1f7a67a2'
down_revision = 'a13fd38a2e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_data_tbl', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_data_tbl', 'image_url')
    # ### end Alembic commands ###
