"""add class_color in classesandtags  models

Revision ID: ef05d8830fd7
Revises: c39eeec2f026
Create Date: 2025-01-03 10:32:40.478734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef05d8830fd7'
down_revision = 'c39eeec2f026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
