"""Initial migration

Revision ID: f9d3be5e9654
Revises: 
Create Date: 2024-12-23 00:05:09.610140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9d3be5e9654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('user_photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('menu_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('ANNOTATIONS', 'VIDEO_EDITOR', 'IMAGE_EDITOR', 'TEXT_EDITOR', 'AUDIO_EDITOR', 'DATASET_SPLIT', 'DOCUMENT_EDITOR', 'JSON_EDITOR', 'URL_EXTRACTOR', 'IMAGE_COLOR_PICKER', 'REGEX_EDITOR', 'CRYPTOGRAPHY_GENERATOR', name='menustype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('menu_metadata', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_menu_tbl_id'), 'menu_tbl', ['id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('delivery_type', postgresql.ENUM('EMAIL', 'SMS', 'WHATSAPP', name='deliverytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_verification_codes_phone_number'), 'verification_codes', ['phone_number'], unique=False)
    op.create_table('annotation_projects_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('annotation_type', sa.Enum('COMPUTER_VISION', 'NLP', 'AUDIO', 'CONVERSATIONAL_AI', 'RANKING_SCORING', 'STRUCTURED_DATA_PARSING', 'TIME_SERIES_ANALYSIS', 'VIDEO', 'GENERATIVE_AI', name='annotationtype'), nullable=False),
    sa.Column('project_photo_url', sa.String(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_annotation_projects_tbl_id'), 'annotation_projects_tbl', ['id'], unique=False)
    op.create_table('annotation_project_data_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_data_tbl_id'), 'annotation_project_data_tbl', ['id'], unique=False)
    op.create_table('annotation_project_deployments_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_deployments_tbl_id'), 'annotation_project_deployments_tbl', ['id'], unique=False)
    op.create_table('annotation_project_models_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['annotation_projects_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_project_models_tbl_id'), 'annotation_project_models_tbl', ['id'], unique=False)
    op.create_table('active_learning_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['annotation_project_deployments_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_learning_tbl_id'), 'active_learning_tbl', ['id'], unique=False)
    op.create_table('annotate_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inner_id', sa.String(), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('annotated_by', sa.Integer(), nullable=True),
    sa.Column('annotation_results', sa.Text(), nullable=True),
    sa.Column('annotation_ids', sa.Text(), nullable=True),
    sa.Column('prediction_score', sa.String(), nullable=True),
    sa.Column('prediction_model_versions', sa.Text(), nullable=True),
    sa.Column('prediction_results', sa.Text(), nullable=True),
    sa.Column('upload_filename', sa.String(), nullable=True),
    sa.Column('storage_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('drafts', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['annotated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inner_id')
    )
    op.create_index(op.f('ix_annotate_tbl_id'), 'annotate_tbl', ['id'], unique=False)
    op.create_table('classes_and_tags_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_and_tags_tbl_id'), 'classes_and_tags_tbl', ['id'], unique=False)
    op.create_table('dataset_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_tbl_id'), 'dataset_tbl', ['id'], unique=False)
    op.create_table('deployment_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['annotation_project_deployments_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_tbl_id'), 'deployment_tbl', ['id'], unique=False)
    op.create_table('models_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['annotation_project_models_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_tbl_id'), 'models_tbl', ['id'], unique=False)
    op.create_table('train_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_tbl_id'), 'train_tbl', ['id'], unique=False)
    op.create_table('upload_data_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_data_tbl_id'), 'upload_data_tbl', ['id'], unique=False)
    op.create_table('version_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['annotation_project_data_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_tbl_id'), 'version_tbl', ['id'], unique=False)
    op.create_table('annotate_result_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotate_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.Enum('OBJECT_DETECTION', 'SEMANTIC_SEGMENTATION', 'TEXT_CLASSIFICATION', 'AUDIO_TRANSCRIPTION', 'AUDIO_CLASSIFICATION', 'NLP_ENTITIES', name='annotateresulttypeenum'), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=True),
    sa.Column('y1', sa.Integer(), nullable=True),
    sa.Column('x2', sa.Integer(), nullable=True),
    sa.Column('y2', sa.Integer(), nullable=True),
    sa.Column('text_result', sa.Text(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotate_id'], ['annotate_tbl.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotate_result_tbl_id'), 'annotate_result_tbl', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotate_result_tbl_id'), table_name='annotate_result_tbl')
    op.drop_table('annotate_result_tbl')
    op.drop_index(op.f('ix_version_tbl_id'), table_name='version_tbl')
    op.drop_table('version_tbl')
    op.drop_index(op.f('ix_upload_data_tbl_id'), table_name='upload_data_tbl')
    op.drop_table('upload_data_tbl')
    op.drop_index(op.f('ix_train_tbl_id'), table_name='train_tbl')
    op.drop_table('train_tbl')
    op.drop_index(op.f('ix_models_tbl_id'), table_name='models_tbl')
    op.drop_table('models_tbl')
    op.drop_index(op.f('ix_deployment_tbl_id'), table_name='deployment_tbl')
    op.drop_table('deployment_tbl')
    op.drop_index(op.f('ix_dataset_tbl_id'), table_name='dataset_tbl')
    op.drop_table('dataset_tbl')
    op.drop_index(op.f('ix_classes_and_tags_tbl_id'), table_name='classes_and_tags_tbl')
    op.drop_table('classes_and_tags_tbl')
    op.drop_index(op.f('ix_annotate_tbl_id'), table_name='annotate_tbl')
    op.drop_table('annotate_tbl')
    op.drop_index(op.f('ix_active_learning_tbl_id'), table_name='active_learning_tbl')
    op.drop_table('active_learning_tbl')
    op.drop_index(op.f('ix_annotation_project_models_tbl_id'), table_name='annotation_project_models_tbl')
    op.drop_table('annotation_project_models_tbl')
    op.drop_index(op.f('ix_annotation_project_deployments_tbl_id'), table_name='annotation_project_deployments_tbl')
    op.drop_table('annotation_project_deployments_tbl')
    op.drop_index(op.f('ix_annotation_project_data_tbl_id'), table_name='annotation_project_data_tbl')
    op.drop_table('annotation_project_data_tbl')
    op.drop_index(op.f('ix_annotation_projects_tbl_id'), table_name='annotation_projects_tbl')
    op.drop_table('annotation_projects_tbl')
    op.drop_index(op.f('ix_verification_codes_phone_number'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_menu_tbl_id'), table_name='menu_tbl')
    op.drop_table('menu_tbl')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
