"""Initial migration

Revision ID: ff69403638da
Revises: ff75ff2649d0
Create Date: 2024-12-24 15:15:13.321025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff69403638da'
down_revision = 'ff75ff2649d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
